- name: loopback address
  ansible.builtin.copy:
    src: files/lo.network
    dest: /etc/systemd/network/lo.network
    owner: root
    group: root
    mode: '644'
  notify: restart systemd-networkd
  become: yes
